-- WaffleFinance coordinator persistence schema.
-- This DB is treated as a CACHE — the source of truth is always the
-- on-chain state of the HTLC contracts on both chains. The coordinator
-- can rebuild this DB by re-reading events from both chains.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS orders (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    -- Globally unique id used by clients. We use a UUID-shaped hex
    -- string generated by the coordinator at announce time.
    public_id             TEXT    NOT NULL UNIQUE,

    direction             TEXT    NOT NULL CHECK (direction IN ('eth_to_xlm', 'xlm_to_eth', 'eth_to_sol', 'sol_to_eth')),
    status                TEXT    NOT NULL CHECK (status IN ('announced', 'src_locked', 'dst_locked', 'secret_revealed', 'completed', 'refunded', 'failed', 'expired', 'cancelled', 'abandoned')),

    -- Cross-chain link.
    hashlock              TEXT    NOT NULL,    -- 0x-prefixed 32-byte hex.

    -- Source chain (where the user locks first).
    src_chain             TEXT    NOT NULL CHECK (src_chain IN ('ethereum', 'stellar', 'solana')),
    src_address           TEXT    NOT NULL,    -- user's address on src.
    src_asset             TEXT    NOT NULL,    -- "native" or contract id.
    src_amount            TEXT    NOT NULL,    -- decimal string (atomic units).
    src_safety_deposit    TEXT    NOT NULL,    -- decimal string.
    src_order_id          TEXT,                -- on-chain order id once locked.
    src_lock_tx           TEXT,
    src_lock_block        INTEGER,
    src_timelock          INTEGER,             -- unix seconds (absolute).

    -- Destination chain (where the user wants to receive).
    dst_chain             TEXT    NOT NULL CHECK (dst_chain IN ('ethereum', 'stellar', 'solana')),
    dst_address           TEXT    NOT NULL,
    dst_asset             TEXT    NOT NULL,
    dst_amount            TEXT    NOT NULL,
    dst_order_id          TEXT,
    dst_lock_tx           TEXT,
    dst_lock_block        INTEGER,
    dst_timelock          INTEGER,

    -- Secret tracking. preimage stays NULL until revealed.
    -- When encryption is enabled (SECRET_STORAGE_KEY is set), preimage holds
    -- a base64url-encoded AES-256-GCM blob instead of a raw hex string.
    -- The enc_version column tracks the storage format:
    --   NULL  → plaintext (legacy / encryption disabled)
    --   1     → AES-256-GCM encrypted blob (see coordinator/src/crypto/secret-cipher.ts)
    preimage              TEXT,
    preimage_enc_version  INTEGER,
    secret_revealed_tx    TEXT,

    -- Resolver that filled the destination side (if any).
    resolver_address      TEXT,

    -- Per-order reconciler high-water marks (see 011_order_ledger_cursors.sql).
    last_eth_block        INTEGER,
    last_soroban_ledger   INTEGER,
    last_solana_slot      INTEGER,

    -- Reason this order was cancelled or abandoned (see 012_order_cancellation.sql).
    cancellation_reason   TEXT,

    created_at            INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER)),
    updated_at            INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER)),
    archived_at           INTEGER
);

CREATE INDEX IF NOT EXISTS idx_orders_hashlock         ON orders (hashlock);
CREATE INDEX IF NOT EXISTS idx_orders_src_address      ON orders (src_address);
CREATE INDEX IF NOT EXISTS idx_orders_dst_address      ON orders (dst_address);
CREATE INDEX IF NOT EXISTS idx_orders_status           ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_src_order_id     ON orders (src_chain, src_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_dst_order_id     ON orders (dst_chain, dst_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_public_id        ON orders (public_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at       ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_src_address_created_at ON orders (src_address, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_dst_address_created_at ON orders (dst_address, created_at DESC);

-- Cursor-based pagination indexes (see migrations/005_cursor_pagination.sql).
CREATE INDEX IF NOT EXISTS idx_orders_cursor_pagination ON orders (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_orders_src_cursor ON orders (src_address, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_orders_dst_cursor ON orders (dst_address, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_orders_last_eth_block ON orders (last_eth_block) WHERE last_eth_block IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_last_soroban_ledger ON orders (last_soroban_ledger) WHERE last_soroban_ledger IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_last_solana_slot ON orders (last_solana_slot) WHERE last_solana_slot IS NOT NULL;

CREATE TABLE IF NOT EXISTS order_events (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id      INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    event_type    TEXT    NOT NULL,
    payload_json  TEXT    NOT NULL,
    created_at    INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER))
);

CREATE INDEX IF NOT EXISTS idx_order_events_order ON order_events (order_id, created_at);

CREATE TABLE IF NOT EXISTS resolver_heartbeats (
    address     TEXT PRIMARY KEY,
    chain       TEXT NOT NULL CHECK (chain IN ('ethereum', 'stellar')),
    last_seen   INTEGER NOT NULL
);

-- Schema migration history.
-- Each row records one logical migration that has been applied to this database.
-- For SQLite the coordinator applies all migrations atomically via schema.sql;
-- rows are seeded at first open with duration_ms = 0.  Subsequent opens are
-- idempotent (INSERT OR IGNORE).  Querying this table via queryMigrations()
-- lets operators confirm which migrations are present.
CREATE TABLE IF NOT EXISTS schema_migrations (
    migration   TEXT    PRIMARY KEY,
    applied_at  INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL
);


-- ── Audit log ─────────────────────────────────────────────────────────────────
-- Durable, append-only record of order lifecycle transitions and recovery
-- actions.  Rows are never updated or deleted.
-- See coordinator/src/audit/audit-log.ts for the full type contract.

CREATE TABLE IF NOT EXISTS audit_log (
    id             INTEGER  PRIMARY KEY AUTOINCREMENT,
    schema_version INTEGER  NOT NULL DEFAULT 1,
    event_type     TEXT     NOT NULL,
    order_id       TEXT,
    request_id     TEXT,
    payload_json   TEXT     NOT NULL,
    created_at     INTEGER  NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER))
);

CREATE INDEX IF NOT EXISTS idx_audit_log_order_id
    ON audit_log (order_id, id ASC)
    WHERE order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_log_id_asc
    ON audit_log (id ASC);

CREATE INDEX IF NOT EXISTS idx_audit_log_event_type
    ON audit_log (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
    ON audit_log (created_at DESC);

-- ── Chain cursors ─────────────────────────────────────────────────────────────
-- Tracks the last fully-processed block/ledger/slot per chain so the reconciler
-- can compute the exact gap between "last seen" and "current tip" after a restart.
-- `position` uses the native unit for each chain:
--   ethereum → block number
--   stellar  → ledger sequence number
--   solana   → slot number
-- A missing row means the reconciler has never run for that chain.
CREATE TABLE IF NOT EXISTS chain_cursors (
    chain       TEXT    PRIMARY KEY CHECK (chain IN ('ethereum', 'stellar', 'solana')),
    position    INTEGER NOT NULL DEFAULT 0,
    updated_at  INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER))
);

-- ── Soroban listener checkpoints ──────────────────────────────────────────────
-- Durable checkpoint for the Soroban event listener so ingestion can resume
-- safely after a restart, redeploy, or temporary RPC inconsistency without
-- reprocessing from scratch or skipping a missed ledger range.
-- See migrations/010_soroban_checkpoints.sql for the full column contract.
--   contract_id       the Soroban HTLC contract the checkpoint belongs to.
--   last_safe_ledger  highest fully-processed ledger; advances forward only.
--   effective_cursor  opaque Soroban RPC pagination cursor, or NULL after a reset.
--   recovery_marker   'clean' | 'pending_replay' | 'recovering' — drives replay.
--   updated_at        unix timestamp (seconds) of the last checkpoint write.
CREATE TABLE IF NOT EXISTS soroban_checkpoints (
    contract_id      TEXT    PRIMARY KEY,
    last_safe_ledger INTEGER NOT NULL DEFAULT 0,
    effective_cursor TEXT,
    recovery_marker  TEXT    NOT NULL DEFAULT 'clean'
                     CHECK (recovery_marker IN ('clean', 'pending_replay', 'recovering')),
    updated_at       INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER))
);

